### ISSUE TITLE
Choose a single logging library?

### ISSUE THREAD

**Issue by alanshaw** [drand/drand#290]
Does drand need multiple logging libraries? Can we standardize on one? We have:

* ipfs/go-log
* go-kit/kit/log
* nikkolasg/slog

**Comment by willscott** [comment]
I think i may have recently introduced the IPFS log 😅 
Happy to standardize - It would be nice if we can get output to show up as both a machine structured (e.g. json records) and human readable format.
I don't think i have other preferences.
if there's a choice of one we like, happy to go back and try to standardize on it.

**Comment by nikkolasg** [comment]
I've spent some time looking at loggers and go-kit's logger is quite nice since it's key values pairs `key=value` type of log and still readable. so not JSON but definitely machine readable. And go-kit is quite used and tries to expose best practice for many aspects of using golang. 
slog should be deprecated but it's just being used for the CLI : how to show information to the user. Here it's not even called "logging" it's purely CLI output.

**Comment by willscott** [comment]
we're now using `github.com/drand/drand/log` throughout - there may be a few remaining uses of the go-log. In general, the choice is made though, and this issue is resolved.
