### ISSUE TITLE
HTTP Relay: pooling

### ISSUE THREAD

**Issue by hsanjuan** [drand/drand#381]
The HTTP relay should hold any connection for the next round until it is produced, at which point it returns the value. This hopefully allows CDNs to do pooling.

Perhaps, we should put this under a separate endpoint `/public/next`. I am thinking that otherwise we might get really bad metrics for the rounds endpoints (effectively 29s of mean request time), which is bad to detect service degradations. Thoughts @willscott ?

**Comment by willscott** [comment]
the first part "having pooling" is something we already do. when you ask for a round that the http relay believes is forthcoming, you'll get a response that's held open until it's available.

I don't have strong thoughts about if that'll affect metrics - it's worth noting that currently you'll only get the behavior when you ask for the specific round number of the current round, so it is any any given moment a distinct URL that'll hold - not sure if that distinguishes it from other url endpoints.

I think `/next` isn't sufficient because the client should be explicit in what data they're looking for. if there's a race, and the client ends up blocking on data that's already available, that's a weird failure mode we shouldn't have to deal with.

**Comment by hsanjuan** [comment]
After a quick chat we said we would add `/public/<round>/longpoll` or similar to differentiate requests for a given round that should return asap or fail from requests that will last until a new round is generated.

Regarding the problem of longpolling not working, I cannot reproduce anymore.

**Comment by AnomalRoil** [comment]
If you need this, feel free to re-open. For now we expect the client to handle retries in a timely fashion.
