### ISSUE TITLE
`/public/latest` Expires headers might be in the past if drand stopped generating randomness

### ISSUE THREAD

**Issue by hsanjuan** [drand/drand#462]
Unless I'm wrong, I think the API `/public/latest` continues to provide the last-issued randomness value even if the network is not generating randomness. This means that the dates caching headers will be already expired.

This would mean that if the network stops producing randomness, any CDN is essentially disabled for this endpoint. I am not sure we can have a good fix here (ideas?). The http-relays should cache the latest value though, if they don't already.

**Comment by nikkolasg** [comment]
The http server will only avoid a request to the node if client is asking for latest round server has stored +1 ([code](https://github.com/drand/drand/blob/master/http/server.go#L158)) , right ?
That means when drand is stopped, server may will indeed request to the drand node if the client ask for what the current round should be (for example 10 more round later as to what the http server stored). 

What we could do here is to simply say client can only asks the round+1 of the latest stored and refuse / reject requests for rounds later than that. 
That way even when drand is down, http server wont forward the request of "current rounds", until they see that the network produces values again.
cc/ @willscott

**Comment by nikkolasg** [comment]
>Can we cache the latest round so that that request doesn't the hit the drand node more than ~once? 

I believe that is already the case.
What I am saying if is the drand network is down for multiple rounds, client can ask multiple rounds to the http server and the http server have to ask the drand node in this case because these rounds _should_ have hapenned but server doesn't have it.
In that case, we can say that http server only ask drand nodes for the last round stored + 1 (and he is bulking the request already for that case), so in the scenario I just described, clients will get an error / special http header directly and drand node is not asked.
