### ISSUE TITLE
404 / 500 - Latest Randomness - Website

### ISSUE THREAD

**Issue by tranzium** [drand/drand#802]
When visiting the website (drand.love) at the refresh interval (i.e. every 00 and 30 seconds), the generation of the latest randomness fails with either a 404 or 500 error.

Examples:
Error: unexpected HTTP status 500 for URL https://drand.cloudflare.com/public/1014897
Error: unexpected HTTP status 500 for URL https://drand.cloudflare.com/public/1014903
Error: unexpected HTTP status 404 for URL https://drand.cloudflare.com/public/1014904

Hypothesis: The website knows how to generate the next available randomness without actually fetching the next available randomness and thus, is calling it prior to its existence.

Possible solution 1: Retry button

Possible solution 2: If existence is inevitable, ignore errors and continue to request (latest) randomness until success.

**Comment by willscott** [comment]
I think this is an issue between the cloudflare CDN and the way drand has been expecting to buffer the upcoming round of randomness (cc @lukevalenta )

In general, we expect that the beacon for a round will become available some milliseconds after the official round time, one sufficient partial shares have been distributed that each node is able to reconstruct the beacon.
The drand http gateway handles this by holding inbound connections for rounds that haven't been released yet open until the round is received and then sending them out.

We believe the cloudflare CDN sees these long-lived connections as potential DOS vectors to the origin server, and closes them proactively rather than letting them wait until the round is produced.

The 404 should only be received if you request a round more than 30 seconds in the future.

**Comment by lukevalenta** [comment]
Thanks for reporting! This behavior was not intentional and should now be resolved. Could you check that the issue is resolved, and reopen this ticket if that's not the case?

The issue first appeared when the metal the nodes were running on in our k8s cluster was rebooted on Friday. I suspect it may be a clock sync issue on the new metal they were rebooted on that prevented the drand origin from correctly pooling connections, but haven't yet verified that hypothesis. I'll update this issue if I'm able to get to the bottom of it.

**Comment by tranzium** [comment]
Issue has been resolved. Thank you.
