### ISSUE TITLE
Have a `resync` command

### ISSUE THREAD

**Issue by AnomalRoil** [drand/drand#919]
The `resync` should:

- go through all the beacons in the database and check everything is there and valid
- if it finds broken or missing entries, it should pull the proper data from other nodes (at least a threshold of them)

This should allow us to detect storage issues and correct them.

**Comment by AnomalRoil** [comment]
cc @hsanjuan any more requirements on what it should do?

**Comment by nikkolasg** [comment]
> if it finds broken or missing entries, it should pull the proper data from other nodes (at least a threshold of them)

One is enough since that data is verifiable :) 

I think we could even put this feature inside the already existing sync command ? Just for the CLI aspect, to avoid putting more and more commands.
The existing sync commands could look if there is already a database and resync from scratch if we tell it to, and do the verification. 
wdyt ?

**Comment by AnomalRoil** [comment]
True, I was thinking about partials and not about already issued beacons, we def don't need a threshold of these.

Are you talking of the current `drand follow --sync-nodes` CLI or something else?

**Comment by hsanjuan** [comment]
> cc @hsanjuan any more requirements on what it should do?

Perhaps a `check` command that just reports if there are rounds missing and which and how many, and a `repair` or `resync` command to fetch them/store them. But it also works for me as proposed.

**Comment by AnomalRoil** [comment]
Example rounds on mainnet we need to test resync on:
- 1974205
- 1974232
- 1958962
